---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: {{ include "ack-autoscaling-controller.app.fullname" . }}-writer
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "ack-autoscaling-controller.app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    k8s-app: {{ include "ack-autoscaling-controller.app.name" . }}
    helm.sh/chart: {{ include "ack-autoscaling-controller.chart.name-version" . }}
rules:
- apiGroups:
  - autoscaling.services.k8s.aws
  resources:
  - autoscalinggroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.services.k8s.aws
  resources:
  - autoscalinggroups
  verbs:
  - get
  - patch
  - update
