---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-autoscaling-reader
  namespace: default
rules:
- apiGroups:
  - autoscaling.services.k8s.aws
  resources:
  - autoscalinggroups
  verbs:
  - get
  - list
  - watch
