apiVersion: v1
name: autoscaling-chart
description: A Helm chart for the ACK service controller for Amazon EC2 Auto Scaling (AutoScaling)
version: 0.0.0-non-release-version
appVersion: 0.0.0-non-release-version
home: https://github.com/aws-controllers-k8s/autoscaling-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws-controllers-k8s/autoscaling-controller
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
  - name: AutoScaling Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/autoscaling-maintainer
keywords:
  - aws
  - kubernetes
  - autoscaling
